"""Deterministic mock AI provider for testing.

Returns schema-valid enrichment output based on input findings.
No network calls. No randomness. Fully deterministic.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from pharabius.ai.adapter import AIAdapter, AIResponse
from pharabius.schemas.ai_enrichment import AIUsageSummary


class MockAIAdapter(AIAdapter):
    """Mock provider that returns deterministic schema-valid enrichment.

    For each finding in the context, generates:
    - explanation based on finding title and category
    - risk_rationale referencing evidence
    - recommended_action_refinement with generic suggestion
    - uncertainty_notes about AI nature

    All evidence_ids from the finding are preserved.
    """

    @property
    def name(self) -> str:
        return "mock"

    @property
    def model(self) -> str:
        return "mock-v0.7.0"

    def generate_json(
        self,
        prompt: str,
        context: dict[str, Any],
        schema_hint: dict[str, Any] | None = None,
        *,
        timeout_seconds: int = 30,
    ) -> AIResponse:
        findings = context.get("findings", [])
        evidence_map = context.get("evidence_map", {})

        enrichments: list[dict[str, Any]] = []
        for finding in findings:
            fid = finding.get("id", "")
            title = finding.get("title", "Unknown finding")
            category = finding.get("category", "unknown")
            ev_ids = finding.get("evidence_ids", [])
            severity = finding.get("severity", "Medium")

            # Build mock enrichment preserving evidence linkage
            explanation = (
                f"This {category} finding ({fid}) identifies: {title}. "
                f"Severity is assessed as {severity} based on {len(ev_ids)} evidence item(s)."
            )
            risk_rationale = (
                f"Risk is inferred from {len(ev_ids)} evidence item(s) "
                f"in the {category} category. Validate with the engineering team."
            )
            recommended = (
                f"Review the {len(ev_ids)} linked evidence item(s) for {fid}. "
                f"Prioritize based on {severity} severity and team capacity."
            )
            uncertainty = (
                "This enrichment is generated by a mock provider for testing. "
                "Replace with real provider output in production."
            )

            enrichment: dict[str, Any] = {
                "finding_id": fid,
                "evidence_ids": list(ev_ids),
                "confidence": severity,
                "limitations": [
                    "AI-generated enrichment — validate before acting",
                    f"Based on {len(ev_ids)} evidence item(s)",
                ],
                "title_suggestion": "",
                "explanation": explanation,
                "risk_rationale": risk_rationale,
                "recommended_action_refinement": recommended,
                "verification_refinement": "",
                "uncertainty_notes": uncertainty,
                "grouping_suggestion": "",
                "business_impact_narrative": "",
                "analysis_unit_ids": finding.get("analysis_unit_ids", []),
                "graph_ids": [],
                "evidence_references": [
                    {
                        "evidence_id": eid,
                        "relevance": f"Linked evidence for {fid}",
                        "snippet_used": str(evidence_map.get(eid, ""))[:200],
                    }
                    for eid in ev_ids[:5]  # Cap at 5 references
                ],
                "rejected_claims": [],
            }
            enrichments.append(enrichment)

        raw = json.dumps({"enrichments": enrichments}, indent=2)
        return AIResponse(
            provider=self.name,
            model=self.model,
            raw_text=raw,
            parsed_json={"enrichments": enrichments},
            usage=AIUsageSummary(
                provider=self.name,
                model=self.model,
                prompt_chars=len(prompt),
                response_chars=len(raw),
                items_processed=len(findings),
                items_accepted=len(enrichments),
                items_rejected=0,
            ),
            finish_reason="complete",
            errors=[],
        )


def _hash_text(text: str) -> str:
    """Deterministic hash for audit trail."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
