"""Jira export bundle generator.

Generates repository-local Jira-ready Markdown and CSV artifacts from
Pharabius ticket drafts. No Jira REST API calls are made.
"""

from __future__ import annotations

import csv
import io
import json
import logging
from pathlib import Path

from pharabius.schemas.export_bundles import (
    ExportBundleArtifact,
    ExportBundleFormat,
    TrackerKind,
)
from pharabius.schemas.tickets import TicketDraft, TicketDraftIndex

logger = logging.getLogger(__name__)

JIRA_BUNDLE_DIR = "jira"

CSV_COLUMNS = [
    "Summary",
    "Issue Type",
    "Description",
    "Priority",
    "Labels",
    "Linked Findings",
    "Work Package",
    "Source Ticket Draft",
    "Review Decision",
    "Completeness",
]


def _load_ticket_drafts(ticket_drafts_dir: Path) -> list[TicketDraft]:
    """Load ticket drafts from the JSON index."""
    index_path = ticket_drafts_dir / "ticket-drafts.json"
    if not index_path.exists():
        logger.warning("Ticket draft index not found: %s", index_path)
        return []
    data = json.loads(index_path.read_text(encoding="utf-8"))
    idx = TicketDraftIndex.model_validate(data)
    return [d for d in idx.drafts if d.status == "draft"]


def _render_jira_markdown(drafts: list[TicketDraft]) -> str:
    """Render Jira-flavored Markdown from ticket drafts."""
    lines: list[str] = []
    lines.append("# Jira Ticket Draft Export")
    lines.append("")
    lines.append(
        "> Repository-local export generated by Pharabius. This file does not create Jira issues."
    )
    lines.append("")
    lines.append(f"**Total drafts**: {len(drafts)}")
    lines.append("")

    for d in drafts:
        lines.append(f"## {d.ticket_id}: {d.title}")
        lines.append("")
        lines.append(f"- **Work Package**: {d.source_id}")
        lines.append(f"- **Priority**: {d.priority or 'Unset'}")
        lines.append(f"- **Review Decision**: {d.review_decision or 'not_reviewed'}")
        comp = d.completeness
        lines.append(f"- **Completeness**: {comp.status if comp else 'unknown'}")
        labels = ", ".join(d.labels) if d.labels else "—"
        lines.append(f"- **Labels**: {labels}")
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else "—"
        lines.append(f"- **Linked Findings**: {linked}")
        lines.append("")
        if d.body_markdown:
            lines.append(d.body_markdown)
        lines.append("")

    return "\n".join(lines)


def _render_jira_csv(drafts: list[TicketDraft]) -> str:
    """Render Jira-compatible CSV from ticket drafts."""
    buf = io.StringIO()
    writer = csv.writer(buf, quoting=csv.QUOTE_MINIMAL)
    writer.writerow(CSV_COLUMNS)
    for d in drafts:
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else ""
        labels = ", ".join(d.labels) if d.labels else ""
        comp = d.completeness.status if d.completeness else "unknown"
        writer.writerow(
            [
                d.title,
                "Task",
                (d.body_markdown or "").replace("\n", "\\n"),
                d.priority or "",
                labels,
                linked,
                d.source_id,
                d.artifact_path,
                d.review_decision or "not_reviewed",
                comp,
            ]
        )
    return buf.getvalue()


def _render_jira_readme() -> str:
    """Render Jira bundle README."""
    return (
        "# Jira Export Bundle\n"
        "\n"
        "Repository-local export generated by Pharabius.\n"
        "\n"
        "## What This Contains\n"
        "\n"
        "- `jira-ticket-drafts.md` — Jira-flavored Markdown with all ticket drafts\n"
        "- `jira-ticket-drafts.csv` — CSV suitable for Jira import preparation\n"
        "\n"
        "## What This Does Not Do\n"
        "\n"
        "- Does not call the Jira REST API\n"
        "- Does not create Jira issues\n"
        "- Does not assign projects, sprints, or assignees\n"
        "\n"
        "## How to Use\n"
        "\n"
        "1. Review the Markdown or CSV content\n"
        "2. Copy relevant fields into Jira manually or prepare CSV import\n"
        "3. Add Jira-specific fields (project, sprint, assignee) manually\n"
        "\n"
        "PET teams are responsible for review, import, and assignment.\n"
    )


def generate_jira_export_bundle(
    ticket_drafts_dir: Path,
    output_dir: Path,
    *,
    product_version: str = "",
) -> list[ExportBundleArtifact]:
    """Generate Jira Markdown and CSV export bundle.

    Args:
        ticket_drafts_dir: Path to .ai-debt/ticket-drafts/.
        output_dir: Path to .ai-debt/export-bundles/jira/.
        product_version: Pharabius version for metadata.

    Returns:
        List of ExportBundleArtifact records for the manifest.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    drafts = _load_ticket_drafts(ticket_drafts_dir)

    artifacts: list[ExportBundleArtifact] = []

    # Markdown
    md_path = output_dir / "jira-ticket-drafts.md"
    md_content = _render_jira_markdown(drafts)
    md_path.write_text(md_content, encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.JIRA,
            format=ExportBundleFormat.MARKDOWN,
            relative_path=f"{JIRA_BUNDLE_DIR}/jira-ticket-drafts.md",
            description="Jira Markdown export",
            ticket_count=len(drafts),
        )
    )

    # CSV
    csv_path = output_dir / "jira-ticket-drafts.csv"
    csv_content = _render_jira_csv(drafts)
    csv_path.write_text(csv_content, encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.JIRA,
            format=ExportBundleFormat.CSV,
            relative_path=f"{JIRA_BUNDLE_DIR}/jira-ticket-drafts.csv",
            description="Jira CSV export",
            ticket_count=len(drafts),
        )
    )

    # README
    readme_path = output_dir / "README.md"
    readme_path.write_text(_render_jira_readme(), encoding="utf-8")

    return artifacts
