"""Export bundle summary report generator.

Generates a human-readable Markdown summary report for export bundles.
No external tracker API calls are made.
"""

from __future__ import annotations

import logging
from pathlib import Path

from pharabius.core.export_bundle_validation import (
    check_all_tracker_bundles,
    validate_export_bundle_manifest,
)
from pharabius.schemas.export_bundles import ExportBundleManifest

logger = logging.getLogger(__name__)


def render_export_bundle_summary(
    export_bundles_dir: Path,
    manifest: ExportBundleManifest | None = None,
) -> str:
    """Render export bundle summary report as Markdown.

    Args:
        export_bundles_dir: Path to .ai-debt/export-bundles/.
        manifest: Optional pre-loaded manifest.

    Returns:
        Markdown string for the summary report.
    """
    lines: list[str] = []

    lines.append("# Export Bundle Summary")
    lines.append("")
    lines.append(
        "Repository-local export files generated by Pharabius. "
        "No external tracker APIs were called and no issues were created."
    )
    lines.append("")

    # Generation Summary
    s = manifest.summary if manifest else None
    lines.append("## Generation Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---:|")
    if s:
        lines.append(f"| Total tracker bundles | {s.total_bundles} |")
        lines.append(f"| Total artifacts | {s.total_artifacts} |")
        lines.append(f"| Total ticket drafts exported | {s.total_tickets} |")
        trackers = ", ".join(t.value for t in s.trackers) if s.trackers else "—"
        lines.append(f"| Trackers | {trackers} |")
    else:
        lines.append("| (No manifest loaded) | — |")
    lines.append("")

    # Generated Artifacts
    if manifest and manifest.artifacts:
        lines.append("## Generated Artifacts")
        lines.append("")
        lines.append("| Tracker | Format | Path | Tickets |")
        lines.append("|---|---|---|---:|")
        for art in sorted(manifest.artifacts, key=lambda a: (a.tracker.value, a.format.value)):
            lines.append(
                f"| {art.tracker.value} | {art.format.value} "
                f"| `{art.relative_path}` | {art.ticket_count} |"
            )
        lines.append("")

    # Completeness
    completeness_results = check_all_tracker_bundles(export_bundles_dir)
    if completeness_results:
        lines.append("## Completeness")
        lines.append("")
        lines.append("| Tracker | Status | Missing | Warnings |")
        lines.append("|---|---|---|---:|")
        for c in completeness_results:
            missing = ", ".join(c.missing_artifacts) if c.missing_artifacts else "—"
            lines.append(f"| {c.tracker} | {c.status} | {missing} | {len(c.warnings)} |")
        lines.append("")

    # Validation Issues
    validation = validate_export_bundle_manifest(export_bundles_dir)
    if validation.errors or validation.warnings:
        lines.append("## Validation Issues")
        lines.append("")
        if validation.errors:
            lines.append("### Errors")
            lines.append("")
            for e in validation.errors:
                lines.append(f"- **{e.code}**: {e.message}")
            lines.append("")
        if validation.warnings:
            lines.append("### Warnings")
            lines.append("")
            for w in validation.warnings:
                lines.append(f"- **{w.code}**: {w.message}")
            lines.append("")

    # Safety Boundary
    lines.append("## Safety Boundary")
    lines.append("")
    lines.append("- Pharabius generated repository-local export files only.")
    lines.append("- No external tracker APIs were called.")
    lines.append("- No issues or work items were created.")
    lines.append("- No credentials were used or stored.")
    lines.append("")

    return "\n".join(lines)


def write_export_bundle_summary(
    export_bundles_dir: Path,
    reports_dir: Path,
    manifest: ExportBundleManifest | None = None,
) -> Path:
    """Write the export bundle summary report to disk.

    Args:
        export_bundles_dir: Path to .ai-debt/export-bundles/.
        reports_dir: Path to .ai-debt/reports/.
        manifest: Optional pre-loaded manifest.

    Returns:
        Path to the written report file.
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / "export-bundle-summary.md"
    path.write_text(
        render_export_bundle_summary(export_bundles_dir, manifest),
        encoding="utf-8",
    )
    return path
