"""Linear export bundle generator.

Generates repository-local Linear-ready Markdown and CSV artifacts from
Pharabius ticket drafts. No Linear GraphQL API calls are made.
"""

from __future__ import annotations

import csv
import io
import json
import logging
from pathlib import Path

from pharabius.schemas.export_bundles import (
    ExportBundleArtifact,
    ExportBundleFormat,
    TrackerKind,
)
from pharabius.schemas.tickets import TicketDraft, TicketDraftIndex

logger = logging.getLogger(__name__)

LINEAR_BUNDLE_DIR = "linear"

CSV_COLUMNS = [
    "Title",
    "Description",
    "Priority",
    "Labels",
    "Linked Findings",
    "Work Package",
    "Source Ticket Draft",
    "Review Decision",
    "Completeness",
]

# Conservative priority mapping (Pharabius → Linear suggestion)
PRIORITY_MAP: dict[str, str] = {
    "Critical": "Urgent",
    "High": "High",
    "Medium": "Medium",
    "Low": "Low",
}


def _load_ticket_drafts(ticket_drafts_dir: Path) -> list[TicketDraft]:
    """Load ticket drafts from the JSON index."""
    index_path = ticket_drafts_dir / "ticket-drafts.json"
    if not index_path.exists():
        logger.warning("Ticket draft index not found: %s", index_path)
        return []
    data = json.loads(index_path.read_text(encoding="utf-8"))
    idx = TicketDraftIndex.model_validate(data)
    return [d for d in idx.drafts if d.status == "draft"]


def _map_priority(priority: str | None) -> str:
    """Map Pharabius priority to Linear priority suggestion."""
    if priority and priority in PRIORITY_MAP:
        return PRIORITY_MAP[priority]
    return "No priority"


def _render_linear_markdown(drafts: list[TicketDraft]) -> str:
    """Render Linear-flavored Markdown from ticket drafts."""
    lines: list[str] = []
    lines.append("# Linear Ticket Draft Export")
    lines.append("")
    lines.append(
        "> Repository-local export generated by Pharabius. This file does not create Linear issues."
    )
    lines.append("")
    lines.append(f"**Total drafts**: {len(drafts)}")
    lines.append("")

    for d in drafts:
        lines.append(f"## {d.ticket_id}: {d.title}")
        lines.append("")
        lines.append(f"- **Work Package**: {d.source_id}")
        lines.append(f"- **Priority**: {_map_priority(d.priority)}")
        lines.append(f"- **Review Decision**: {d.review_decision or 'not_reviewed'}")
        comp = d.completeness
        lines.append(f"- **Completeness**: {comp.status if comp else 'unknown'}")
        labels = ", ".join(d.labels) if d.labels else "—"
        lines.append(f"- **Labels**: {labels}")
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else "—"
        lines.append(f"- **Linked Findings**: {linked}")
        lines.append("")
        if d.body_markdown:
            lines.append(d.body_markdown)
        lines.append("")

    return "\n".join(lines)


def _render_linear_csv(drafts: list[TicketDraft]) -> str:
    """Render Linear-oriented CSV from ticket drafts."""
    buf = io.StringIO()
    writer = csv.writer(buf, quoting=csv.QUOTE_MINIMAL)
    writer.writerow(CSV_COLUMNS)
    for d in drafts:
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else ""
        labels = ", ".join(d.labels) if d.labels else ""
        comp = d.completeness.status if d.completeness else "unknown"
        writer.writerow(
            [
                d.title,
                (d.body_markdown or "").replace("\n", "\\n"),
                _map_priority(d.priority),
                labels,
                linked,
                d.source_id,
                d.artifact_path,
                d.review_decision or "not_reviewed",
                comp,
            ]
        )
    return buf.getvalue()


def _render_linear_readme() -> str:
    """Render Linear bundle README."""
    return (
        "# Linear Export Bundle\n"
        "\n"
        "Repository-local export generated by Pharabius.\n"
        "\n"
        "## What This Contains\n"
        "\n"
        "- `linear-ticket-drafts.md` — Linear-flavored Markdown\n"
        "- `linear-ticket-drafts.csv` — CSV for Linear import preparation\n"
        "\n"
        "## Priority Mapping\n"
        "\n"
        "Pharabius priorities are mapped conservatively:\n"
        "\n"
        "| Pharabius | Linear Suggestion |\n"
        "|---|---|\n"
        "| Critical | Urgent |\n"
        "| High | High |\n"
        "| Medium | Medium |\n"
        "| Low | Low |\n"
        "\n"
        "These are suggestions only. PET teams should adjust.\n"
        "\n"
        "## What This Does Not Do\n"
        "\n"
        "- Does not call the Linear GraphQL API\n"
        "- Does not create Linear issues\n"
        "- Does not assign teams, projects, or cycles\n"
        "\n"
        "PET teams are responsible for review, import, and assignment.\n"
    )


def generate_linear_export_bundle(
    ticket_drafts_dir: Path,
    output_dir: Path,
    *,
    product_version: str = "",
) -> list[ExportBundleArtifact]:
    """Generate Linear Markdown and CSV export bundle.

    Args:
        ticket_drafts_dir: Path to .ai-debt/ticket-drafts/.
        output_dir: Path to .ai-debt/export-bundles/linear/.
        product_version: Pharabius version for metadata.

    Returns:
        List of ExportBundleArtifact records for the manifest.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    drafts = _load_ticket_drafts(ticket_drafts_dir)

    artifacts: list[ExportBundleArtifact] = []

    # Markdown
    md_path = output_dir / "linear-ticket-drafts.md"
    md_path.write_text(_render_linear_markdown(drafts), encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.LINEAR,
            format=ExportBundleFormat.MARKDOWN,
            relative_path=f"{LINEAR_BUNDLE_DIR}/linear-ticket-drafts.md",
            description="Linear Markdown export",
            ticket_count=len(drafts),
        )
    )

    # CSV
    csv_path = output_dir / "linear-ticket-drafts.csv"
    csv_path.write_text(_render_linear_csv(drafts), encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.LINEAR,
            format=ExportBundleFormat.CSV,
            relative_path=f"{LINEAR_BUNDLE_DIR}/linear-ticket-drafts.csv",
            description="Linear CSV export",
            ticket_count=len(drafts),
        )
    )

    # README
    (output_dir / "README.md").write_text(_render_linear_readme(), encoding="utf-8")

    return artifacts
