"""Azure DevOps export bundle generator.

Generates repository-local Azure DevOps-ready Markdown and CSV artifacts
from Pharabius ticket drafts. No Azure DevOps REST API calls are made.
"""

from __future__ import annotations

import csv
import io
import json
import logging
from pathlib import Path

from pharabius.schemas.export_bundles import (
    ExportBundleArtifact,
    ExportBundleFormat,
    TrackerKind,
)
from pharabius.schemas.tickets import TicketDraft, TicketDraftIndex

logger = logging.getLogger(__name__)

AZURE_BUNDLE_DIR = "azure-devops"

CSV_COLUMNS = [
    "Title",
    "Work Item Type",
    "Description",
    "Priority",
    "Tags",
    "Linked Findings",
    "Work Package",
    "Source Ticket Draft",
    "Review Decision",
    "Completeness",
]

DEFAULT_WORK_ITEM_TYPE = "User Story"


def _load_ticket_drafts(ticket_drafts_dir: Path) -> list[TicketDraft]:
    """Load ticket drafts from the JSON index."""
    index_path = ticket_drafts_dir / "ticket-drafts.json"
    if not index_path.exists():
        logger.warning("Ticket draft index not found: %s", index_path)
        return []
    data = json.loads(index_path.read_text(encoding="utf-8"))
    idx = TicketDraftIndex.model_validate(data)
    return [d for d in idx.drafts if d.status == "draft"]


def _render_azure_markdown(drafts: list[TicketDraft]) -> str:
    """Render Azure DevOps-flavored Markdown from ticket drafts."""
    lines: list[str] = []
    lines.append("# Azure DevOps Ticket Draft Export")
    lines.append("")
    lines.append(
        "> Repository-local export generated by Pharabius. "
        "This file does not create Azure DevOps work items."
    )
    lines.append("")
    lines.append(f"**Total drafts**: {len(drafts)}")
    lines.append("")

    for d in drafts:
        lines.append(f"## {d.ticket_id}: {d.title}")
        lines.append("")
        lines.append(f"- **Work Item Type**: {DEFAULT_WORK_ITEM_TYPE}")
        lines.append(f"- **Work Package**: {d.source_id}")
        lines.append(f"- **Priority**: {d.priority or 'Unset'}")
        lines.append(f"- **Review Decision**: {d.review_decision or 'not_reviewed'}")
        comp = d.completeness
        lines.append(f"- **Completeness**: {comp.status if comp else 'unknown'}")
        tags = "; ".join(d.labels) if d.labels else "—"
        lines.append(f"- **Tags**: {tags}")
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else "—"
        lines.append(f"- **Linked Findings**: {linked}")
        lines.append("")
        if d.body_markdown:
            lines.append(d.body_markdown)
        lines.append("")

    return "\n".join(lines)


def _render_azure_csv(drafts: list[TicketDraft]) -> str:
    """Render Azure Boards-oriented CSV from ticket drafts."""
    buf = io.StringIO()
    writer = csv.writer(buf, quoting=csv.QUOTE_MINIMAL)
    writer.writerow(CSV_COLUMNS)
    for d in drafts:
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else ""
        tags = "; ".join(d.labels) if d.labels else ""
        comp = d.completeness.status if d.completeness else "unknown"
        writer.writerow(
            [
                d.title,
                DEFAULT_WORK_ITEM_TYPE,
                (d.body_markdown or "").replace("\n", "\\n"),
                d.priority or "",
                tags,
                linked,
                d.source_id,
                d.artifact_path,
                d.review_decision or "not_reviewed",
                comp,
            ]
        )
    return buf.getvalue()


def _render_azure_readme() -> str:
    """Render Azure DevOps bundle README."""
    return (
        "# Azure DevOps Export Bundle\n"
        "\n"
        "Repository-local export generated by Pharabius.\n"
        "\n"
        "## What This Contains\n"
        "\n"
        "- `azure-devops-ticket-drafts.md` — Markdown summary\n"
        "- `azure-devops-ticket-drafts.csv` — CSV for Azure Boards\n"
        "\n"
        "## Defaults\n"
        "\n"
        "- **Work Item Type**: User Story (adjust as needed)\n"
        "- **Tags**: Semicolon-separated labels\n"
        "\n"
        "## What This Does Not Do\n"
        "\n"
        "- Does not call the Azure DevOps REST API\n"
        "- Does not create work items\n"
        "- Does not set Area Path, Iteration Path, or Assigned To\n"
        "\n"
        "PET teams are responsible for review, import, and assignment.\n"
    )


def generate_azure_devops_export_bundle(
    ticket_drafts_dir: Path,
    output_dir: Path,
    *,
    product_version: str = "",
) -> list[ExportBundleArtifact]:
    """Generate Azure DevOps Markdown and CSV export bundle.

    Args:
        ticket_drafts_dir: Path to .ai-debt/ticket-drafts/.
        output_dir: Path to .ai-debt/export-bundles/azure-devops/.
        product_version: Pharabius version for metadata.

    Returns:
        List of ExportBundleArtifact records for the manifest.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    drafts = _load_ticket_drafts(ticket_drafts_dir)

    artifacts: list[ExportBundleArtifact] = []

    # Markdown
    md_path = output_dir / "azure-devops-ticket-drafts.md"
    md_path.write_text(_render_azure_markdown(drafts), encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.AZURE_DEVOPS,
            format=ExportBundleFormat.MARKDOWN,
            relative_path=f"{AZURE_BUNDLE_DIR}/azure-devops-ticket-drafts.md",
            description="Azure DevOps Markdown export",
            ticket_count=len(drafts),
        )
    )

    # CSV
    csv_path = output_dir / "azure-devops-ticket-drafts.csv"
    csv_path.write_text(_render_azure_csv(drafts), encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.AZURE_DEVOPS,
            format=ExportBundleFormat.CSV,
            relative_path=f"{AZURE_BUNDLE_DIR}/azure-devops-ticket-drafts.csv",
            description="Azure DevOps CSV export",
            ticket_count=len(drafts),
        )
    )

    # README
    (output_dir / "README.md").write_text(_render_azure_readme(), encoding="utf-8")

    return artifacts
