"""GitHub Issues export bundle generator.

Generates repository-local GitHub Issues-ready Markdown and YAML artifacts
from Pharabius ticket drafts. No GitHub REST or GraphQL API calls are made.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from pharabius.schemas.export_bundles import (
    ExportBundleArtifact,
    ExportBundleFormat,
    TrackerKind,
)
from pharabius.schemas.tickets import TicketDraft, TicketDraftIndex

logger = logging.getLogger(__name__)

GITHUB_BUNDLE_DIR = "github-issues"


def _load_ticket_drafts(ticket_drafts_dir: Path) -> list[TicketDraft]:
    """Load ticket drafts from the JSON index."""
    index_path = ticket_drafts_dir / "ticket-drafts.json"
    if not index_path.exists():
        logger.warning("Ticket draft index not found: %s", index_path)
        return []
    data = json.loads(index_path.read_text(encoding="utf-8"))
    idx = TicketDraftIndex.model_validate(data)
    return [d for d in idx.drafts if d.status == "draft"]


def _render_github_markdown(drafts: list[TicketDraft]) -> str:
    """Render GitHub Issues-flavored Markdown from ticket drafts."""
    lines: list[str] = []
    lines.append("# GitHub Issues Ticket Draft Export")
    lines.append("")
    lines.append(
        "> Repository-local export generated by Pharabius. This file does not create GitHub issues."
    )
    lines.append("")
    lines.append(f"**Total drafts**: {len(drafts)}")
    lines.append("")

    for d in drafts:
        lines.append(f"## {d.ticket_id}: {d.title}")
        lines.append("")
        lines.append(f"- **Work Package**: {d.source_id}")
        lines.append(f"- **Priority**: {d.priority or 'Unset'}")
        lines.append(f"- **Review Decision**: {d.review_decision or 'not_reviewed'}")
        comp = d.completeness
        lines.append(f"- **Completeness**: {comp.status if comp else 'unknown'}")
        labels = ", ".join(d.labels) if d.labels else "—"
        lines.append(f"- **Labels**: {labels}")
        linked = ", ".join(d.linked_debt_items) if d.linked_debt_items else "—"
        lines.append(f"- **Linked Findings**: {linked}")
        lines.append("")
        if d.body_markdown:
            lines.append(d.body_markdown)
        lines.append("")

    return "\n".join(lines)


def _render_issue_yaml(draft: TicketDraft) -> str:
    """Render a single YAML issue draft."""
    comp = draft.completeness
    linked = draft.linked_debt_items or []
    labels = draft.labels or []

    # Build YAML manually for minimal dependency
    lines: list[str] = []
    lines.append("schema_version: '1.0'")
    lines.append(f"source_ticket: '{draft.ticket_id}'")
    # Escape single quotes in title
    title = (draft.title or "").replace("'", "''")
    lines.append(f"title: '{title}'")

    # Labels as YAML list
    lines.append("labels:")
    for lbl in sorted(labels):
        lines.append(f"  - '{lbl}'")
    if not labels:
        lines.append("  []")

    # Linked findings
    lines.append("linked_findings:")
    for f in sorted(linked):
        lines.append(f"  - '{f}'")
    if not linked:
        lines.append("  []")

    lines.append(f"work_package: '{draft.source_id}'")
    lines.append(f"review_decision: '{draft.review_decision or 'not_reviewed'}'")
    lines.append(f"completeness: '{comp.status if comp else 'unknown'}'")

    # Body as literal block scalar
    body = draft.body_markdown or ""
    lines.append("body: |")
    if body:
        for line in body.splitlines():
            lines.append(f"  {line}")
    else:
        lines.append("  ''")

    return "\n".join(lines) + "\n"


def _render_github_readme() -> str:
    """Render GitHub Issues bundle README."""
    return (
        "# GitHub Issues Export Bundle\n"
        "\n"
        "Repository-local export generated by Pharabius.\n"
        "\n"
        "## What This Contains\n"
        "\n"
        "- `github-issues-ticket-drafts.md` — Markdown summary of all drafts\n"
        "- `issues/` — One YAML file per ticket draft\n"
        "\n"
        "## What This Does Not Do\n"
        "\n"
        "- Does not call the GitHub REST or GraphQL API\n"
        "- Does not create GitHub issues\n"
        "- Does not assign milestones, projects, or assignees\n"
        "\n"
        "## How to Use\n"
        "\n"
        "1. Review the Markdown summary\n"
        "2. Inspect individual YAML files in `issues/`\n"
        "3. Create issues manually using the title, labels, and body\n"
        "\n"
        "PET teams are responsible for review and issue creation.\n"
    )


def generate_github_issues_export_bundle(
    ticket_drafts_dir: Path,
    output_dir: Path,
    *,
    product_version: str = "",
) -> list[ExportBundleArtifact]:
    """Generate GitHub Issues Markdown and YAML export bundle.

    Args:
        ticket_drafts_dir: Path to .ai-debt/ticket-drafts/.
        output_dir: Path to .ai-debt/export-bundles/github-issues/.
        product_version: Pharabius version for metadata.

    Returns:
        List of ExportBundleArtifact records for the manifest.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    drafts = _load_ticket_drafts(ticket_drafts_dir)

    artifacts: list[ExportBundleArtifact] = []

    # Markdown
    md_path = output_dir / "github-issues-ticket-drafts.md"
    md_path.write_text(_render_github_markdown(drafts), encoding="utf-8")
    artifacts.append(
        ExportBundleArtifact(
            tracker=TrackerKind.GITHUB_ISSUES,
            format=ExportBundleFormat.MARKDOWN,
            relative_path=f"{GITHUB_BUNDLE_DIR}/github-issues-ticket-drafts.md",
            description="GitHub Issues Markdown export",
            ticket_count=len(drafts),
        )
    )

    # YAML per issue
    issues_dir = output_dir / "issues"
    issues_dir.mkdir(parents=True, exist_ok=True)
    for d in drafts:
        yaml_path = issues_dir / f"{d.ticket_id}.yaml"
        yaml_path.write_text(_render_issue_yaml(d), encoding="utf-8")

    if drafts:
        artifacts.append(
            ExportBundleArtifact(
                tracker=TrackerKind.GITHUB_ISSUES,
                format=ExportBundleFormat.YAML,
                relative_path=f"{GITHUB_BUNDLE_DIR}/issues/",
                description="GitHub Issues YAML drafts",
                ticket_count=len(drafts),
            )
        )

    # README
    (output_dir / "README.md").write_text(_render_github_readme(), encoding="utf-8")

    return artifacts
