from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path

DEFAULT_CONFIG = """\
schema_version: "1.0"

project:
  name: ""
  criticality: "unknown"
  lifecycle: "unknown"

analysis:
  mode: "baseline"
  include_git_history: false
  max_file_size_kb: 500
  exclude_paths:
    - node_modules
    - vendor
    - dist
    - build
    - .git
    - coverage
    - .next
    - target
    - __pycache__

ai:
  enabled: false
  provider: "disabled"
  require_evidence_ids: true

risk_scoring:
  version: "1.0"
  priority_bands:
    low: [0, 10]
    medium: [11, 20]
    high: [21, 35]
    critical: [36, 100]

output:
  directory: ".ai-debt"
  formats:
    - markdown
    - json

policies:
  no_code_modifications: true
  require_confidence: true
  mark_inferred_business_impact: true
"""


README_AI_DEBT = """\
# Pharabius AI Technical Debt Workspace

This directory contains repository-local technical debt intelligence generated by Pharabius.

The v1 workspace is designed to be:

- Evidence-backed
- Repository-local
- Tool-agnostic
- Human-readable
- Machine-readable
- Safe for Product Engineering Team review

Pharabius v1 analyzes and plans. It does not modify production code by default.
"""


PLACEHOLDER_MARKDOWN: dict[str, str] = {
    "debt-register.md": "# Technical Debt Register\n\nNo findings generated yet.\n",
    "architecture-map.md": "# Architecture Map\n\nNo architecture analysis generated yet.\n",
    "dependency-health.md": "# Dependency Health\n\nNo dependency analysis generated yet.\n",
    "test-health.md": "# Test Health\n\nNo test analysis generated yet.\n",
    "security-exposure.md": (
        "# Security and Compliance Exposure\n\nNo security analysis generated yet.\n"
    ),
    "business-risk-proxy.md": (
        "# Business Risk Proxy\n\nNo business-risk analysis generated yet.\n"
    ),
    "remediation-roadmap.md": ("# Remediation Roadmap\n\nNo remediation roadmap generated yet.\n"),
    "handoff-summary.md": (
        "# AI Technical Debt Handoff Summary\n\nNo handoff summary generated yet.\n"
    ),
    "reports/foundation-audit-report.md": (
        "# Foundation Technical Debt Audit Report\n\nNo audit report generated yet.\n"
    ),
}


PLACEHOLDER_JSON: dict[str, dict[str, object]] = {
    "project-profile.json": {
        "schema_version": "1.0",
        "project_name": "",
        "repository_root": "",
        "detected_languages": [],
        "detected_frameworks": [],
        "package_managers": [],
        "build_tools": [],
        "test_frameworks": [],
        "entry_points": [],
        "deployment_files": [],
        "infrastructure_files": [],
        "documentation_files": [],
        "test_directories": [],
        "configuration_files": [],
        "risk_sensitive_areas": [],
        "monorepo": False,
        "services_or_packages": [],
        "analysis_confidence": "Unknown",
        "limitations": ["Repository has not been profiled yet."],
    },
    "evidence.json": {
        "schema_version": "1.0",
        "evidence": [],
    },
    "debt-register.json": {
        "schema_version": "1.0",
        "project_name": "",
        "repository": "",
        "commit": "",
        "branch": "",
        "generated_at": "",
        "summary": {
            "total_findings": 0,
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "top_categories": [],
        },
        "findings": [],
    },
}


def _write_text(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _write_json(path: Path, content: dict[str, object], force: bool) -> bool:
    if path.exists() and not force:
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(content, indent=2) + "\n", encoding="utf-8")
    return True


def initialize_workspace(repository_root: Path, force: bool = False) -> list[Path]:
    workspace = repository_root / ".ai-debt"

    directories: Iterable[Path] = [
        workspace,
        workspace / "work-packages",
        workspace / "reports",
        workspace / "runs",
    ]

    created_or_updated: list[Path] = []

    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
        created_or_updated.append(directory)

    if _write_text(workspace / "README.md", README_AI_DEBT, force):
        created_or_updated.append(workspace / "README.md")

    if _write_text(workspace / "config.yaml", DEFAULT_CONFIG, force):
        created_or_updated.append(workspace / "config.yaml")

    # Governance controls Markdown presentation and handoff policy only.
    # Does NOT change scanner, analyzer, or provider behavior.
    from pharabius.core.governance import default_governance_yaml

    if _write_text(
        workspace / "governance.yaml",
        default_governance_yaml(),
        force,
    ):
        created_or_updated.append(workspace / "governance.yaml")

    for json_path, json_content in PLACEHOLDER_JSON.items():
        target = workspace / json_path
        if _write_json(target, json_content, force):
            created_or_updated.append(target)

    for md_path, md_content in PLACEHOLDER_MARKDOWN.items():
        target = workspace / md_path
        if _write_text(target, md_content, force):
            created_or_updated.append(target)

    return created_or_updated
